### ISSUE TITLE
Error on demo link

### ISSUE THREAD

**Issue by chandrajob365** [ecmadao/react-times#77]
On clicking demo link its giving below error. Operated in Indianapolis timezone
```
Cannot read property 'zoneName' of undefined
TypeError: Cannot read property 'zoneName' of undefined
    at Object.getValidTimeData [as time] (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:175568)
    at Object.<anonymous> (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:837811)
    at __webpack_require__ (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:247)
    at Object.<anonymous> (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:1295541)
    at __webpack_require__ (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:247)
    at Object.<anonymous> (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:1288464)
    at __webpack_require__ (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:247)
    at Object.<anonymous> (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:1273080)
    at __webpack_require__ (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:247)
    at Object.<anonymous> (https://ecmadao.github.io/react-times/static/preview.2a9e6974fe5caf864c3a.bundle.js:1:191828)
```

**Comment by ecmadao** [comment]
It may fixed in next version. Thanks for feedback! @chandrajob365

**Comment by ecmadao** [comment]
v3.1.1 published.
