### ISSUE TITLE
/node_modules/react-times/lib/components/OutsideClickHandler.js:23:113)

### ISSUE THREAD

**Issue by pank0509** [ecmadao/react-times#84]
Hi,
I am using React-times for one of my project.

"react-times": "^1.4.6"

node   8.10.0
npm -v   3.5.2

I am getting error.

`TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/var/www/plexusmd-js-web-frontend/node_modules/react-times/lib/components/OutsideClickHandler.js:23:113)
    at /var/www/plexusmd-js-web-frontend/node_modules/react-times/lib/components/OutsideClickHandler.js:36:3
    at Object.<anonymous> (/var/www/plexusmd-js-web-frontend/node_modules/react-times/lib/components/OutsideClickHandler.js:96:2)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at require.extensions.(anonymous function) (/var/www/plexusmd-js-web-frontend/node_modules/babel-register/lib/node.js:152:7)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/var/www/plexusmd-js-web-frontend/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:260:68)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Module._load (module.js:497:3)`

My code goes like this I have startTime and timeQuantum in state.

`<TimePicker
              focused
              time={(this.state.startTime) ? this.state.startTime : '08:00'}
              theme="material"
              colorPalette="dark"
              timeMode="12"
              onTimeChange={this.handleTimeChange}
              timeQuantum={(this.state.timeQuantum) ? this.state.timeQuantum : 'PM'}
              onTimeQuantumChange={this.timeQuantumChange}
            />`

Can any one help me out.

**Comment by shianqi** [comment]
@pank0509 Hi, [`OutsideClickHandler`](https://github.com/ecmadao/react-times/blob/master/src/components/OutsideClickHandler.jsx#L14) extends from  `PureComponent`，

You can check if the version of React in the project is higher than v15.3.

**Comment by ecmadao** [comment]
react-times is v3.1.0 now, you can update this dependency to check if it solved. @pank0509
